### ISSUE TITLE
Missing Prefab errors

### ISSUE THREAD

**Issue by teknic-atx** [xraxra/IMP#1]
Thanks for posting this project! Unfortunately, when I open in 2018.1, the impostor groups in the demo scene all contain Missing Prefabs. I'm guessing this is due to missing meta files?

**Comment by Shinao** [comment]
I had the same problem on 2018.1, changing Unity version resolved my problem.

**Comment by teknic-atx** [comment]
Which version worked for you?

**Comment by xraxra** [comment]
got it fixed on my end, will be updating the example assets so they are from 2017.3 just to be safe- it is a difference between 2018.1 and 2018.2 prefab serialization

**Comment by xraxra** [comment]
updated the files with 2017.3 ones, it will import without issues

**Comment by teknic-atx** [comment]
Thanks for the update.
